### ISSUE TITLE
[FEATURE] 프론트 작성된 UI에 대한 반응형 작업

### ISSUE THREAD

**Issue by will-kim-querypie** [bear-bear-bear/vanilla-instagram#32]
**어떤 문제에 대한 기능 요청인지 설명**
---
프론트 SCSS 반응형 작업 요청입니다. 모바일 환경에서 사용량이 많은 인스타그램 특성상 필수라고 생각합니다.
8월10일 기준 auth-form템플릿, footer템플릿에 반응형이 적용되어 있지 않습니다.

**원하는 솔루션 설명**
---
모바일 환경도 완벽히 지원하는 반응형 UI.

**해당 솔루션 구현에 대해 고려해본 사항이 있나요?**
---
CSS 에선 매 화면 너비에 대해 media screen을 일일이 작성해야 하지만, SCSS에선 mixin을 이용하여 좀 더 섹시하게 작업 할 수 있습니다. 예시는 아래와 같습니다.
``` SCSS

@mixin for-size($size) {
  @if $size == desktop {
    @media (min-width: 1280.01px) {
      @content;
    }
  } @else if $size == laptop {
    @media (min-width: 1024.01px) and (max-width: 1280px) {
      @content;
    }
  } @else if $size == tablet-portrait {
    @media (min-width: 768.01px) and (max-width: 1024px) {
      @content;
    }
  } @else if $size == tablet-landscape {
    @media (min-width: 768.01px) and (max-width: 1024px) and (orientation: landscape) {
      @content;
    }
  } @else if $size == mobile-landscape {
    @media (min-width: 48.01px) and (max-width: 768px) {
      @content;
    }
  } @else if $size == mobile-portrait {
    @media (min-width: 320.01px) and (max-width: 480px) {
      @content;
    }
  } @else if $size == mobile-fold-portrait {
    @media (min-width: 279px) and (max-width: 320px) {
      @content;
    }
  } @else if $size == mobile-fold-landscape {
    @media (min-width: 650px) and (max-width: 660px) and (max-height: 281px) {
      @content;
    }
  }
}
```

단, 위 mixin은 문제점이 있습니다.
예를 들어보죠.
768px 이하에서만 어떤 스타일을 적용시키고 싶다고 할 때, 우리는 다음과 같은 코드를 작성해야 합니다.
``` scss
h1 {
  font-size: 3rem;

  @include for-size(tablet-portrait) {
    2rem;
  }
  @include for-size(tablet-landscape) {
    2rem;
  }
  @include for-size(mobile-landscape) {
    2rem;
  }
  @include for-size(mobile-portrait) {
    2rem;
  }
  @include for-size(mobile-fold-portrait) {
    2rem;
  }
  @include for-size(mobile-fold-landscape) {
    2rem;
  }
}

```
for-size 구성을 분석해보면, 아래와 같이 위 include를 하나로 줄일 mixin을 추가로 작성할 수 있단걸 알 수 있습니다.
``` scss
h1 {
  font-size: 3rem;

  @include for-mobile {
    font-size: 2rem;
  }
}
```

for-size 를 추가하고 해당 mixin을 분석하고 활용하여 각각 768px, 1024px, 1280px breakpoint 이하에서 동작하는 for-mobile, for-tablet, for-laptop mixin 또한 추가해주세요.
