### ISSUE TITLE
[BUG] footer 템플릿에서 footer 엘리먼트에 직접 스타일을 부여한 문제

### ISSUE THREAD

**Issue by will-kim-querypie** [bear-bear-bear/vanilla-instagram#47]
버그 설명
---
footer 엘리먼트에 직접 스타일을 부여하면, 컴파일 시에 다른 footer 에게도 영향을 미치게 됩니다.
페이지 내 footer는 하나가 아닙니다.
![image](https://user-images.githubusercontent.com/57123802/129487909-c25a41c4-2d2d-4bf2-9ae4-564fd9635080.png)

<br>
<br>

재현하기 위해
---
1. footer를 포함한 페이지를 빌드
2. CSS 빌드 결과 확인
<br>
<br>

스크린샷
---
``` css
...
footer {
  align-items: center;
  display: flex;
  flex-direction: column;
  margin-bottom: 2.5rem;
}
footer,
footer nav {
  width: 100%;
}
footer nav .navigator__list {
  align-items: baseline;
  display: flex;
  flex-wrap: wrap;
  gap: 0.66rem;
  justify-content: center;
  width: 100%;
}
footer nav a {
  text-decoration: none;
}
...
```
<br>
<br>

추가 내용
---
문제에 대한 추가 내용이 있다면 여기에 적어주세요.
